name: github pages

on:
  workflow_dispatch:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup Node
      uses: actions/setup-node@v5
      with:
        node-version: '22'
        cache: 'npm'

    - name: Install
      run: npm ci

    - name: Build
      run: npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
